scrape_configs:  
  - job_name: "<insert-job-name>"  
    scrape_interval: 10s  
    metrics_path: /metrics  
    scheme: https  
    basic_auth:  
      username: <prometheus-username>  
      password: <prometheus-password>  
    http_sd_configs:  
      - url: <url-of-the-service-discovery-configuration>  
        refresh_interval: 60s  
        basic_auth:  
          username: <prometheus-username>  
          password: <prometheus-password>
